cluster.name: os-cluster
network.host: 0.0.0.0

bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping

cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 93%
cluster.routing.allocation.disk.watermark.high: 95%

plugins.security.allow_unsafe_democertificates: true
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemtrustedcas_filepath: certificates/ca/ca.pem
plugins.security.ssl.transport.enabled: true
plugins.security.ssl.transport.pemtrustedcas_filepath: certificates/ca/ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false

plugins.security.authcz.admin_dn:
  - "CN=ADMIN,O=ARKELO,L=JAKARTA,ST=IDF,C=ID"
plugins.security.nodes_dn:
  - "CN=os00,O=ARKELO,L=JAKARTA,ST=IDF,C=ID"
  - "CN=os01,O=ARKELO,L=JAKARTA,ST=IDF,C=ID"
  - "CN=os02,O=ARKELO,L=JAKARTA,ST=IDF,C=ID"
  - "CN=os03,O=ARKELO,L=JAKARTA,ST=IDF,C=ID"
  - "CN=os04,O=ARKELO,L=JAKARTA,ST=IDF,C=ID"
  - "CN=os05,O=ARKELO,L=JAKARTA,ST=IDF,C=ID"
  - "CN=os06,O=ARKELO,L=JAKARTA,ST=IDF,C=ID"
  - "CN=os07,O=ARKELO,L=JAKARTA,ST=IDF,C=ID"
